### DISCUSSION TITLE
Reuse SQL between providers layers

### DISCUSSION THREAD

**Discussion by leeran88** [go-spatial/tegola#964] [Q&A]
Hi!
I have a provider with 3 layers, with the same SQL query (with parameters).

**Is it possible to share the SQL query between the layers?** I want to avoid duplicating them in the config.

Worth to mention - I separated them because the have different geometry types (point, polygon, linestring)

**Comment by ARolek** [comment]
@leeran88 Have you tried pointing different map layers to the same provider layer?

**Reply by leeran88** [reply]
@ARolek I defined 3 layers because they have different geometry types, but the SQL look identical because of the use of parameters. Here's the main idea of my config:

```toml
[[providers]]
name = "locations"
type = "mvt_postgis"
host = "..."
port = 5432
database = "..."
user = "..."
password = "..."
srid = 4326

[[providers.layers]]
name = "points"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "mvt_id"
fields = [ "id", "mvt_id", "name" ]
sql = "..."

[[providers.layers]]
name = "polygons"
geometry_fieldname = "geometry"
geometry_type = "polygon"
id_fieldname = "mvt_id"
fields = [ "id", "mvt_id", "name" ]
sql = "..."

[[providers.layers]]
name = "linestrings"
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "mvt_id"
fields = [ "id", "mvt_id", "name" ]
sql = "..."
```
