### ISSUE TITLE
Debug outline without ?debug=true

### ISSUE THREAD

**Issue by sanfilippopablo** [go-spatial/tegola#287]
Hi. I'm getting the debug outline no matter how I made the request. I tried without ?debug=true and with ?debug=false.

I'm using v0.5.0.

This is my conf.toml:
````toml
[webserver]
port = ":8000"

[cache]
type = "file"
basepath = "/cache"

# register data providers
[[providers]]
name = "db"           # provider name is referenced from map layers
type = "postgis"        # the type of data provider. currently only supports postgis
host = "mydbhost"      # postgis database host
port = 5432             # postgis database port
database = "mydb"       # postgis database name
user = "mydbuser"         # postgis database user
password = "mydbpassword"           # postgis database password
srid = 4326             # The default srid for this provider. If not provided it will be WebMercator (3857)

  [[providers.layers]]
  name = "mylayer"
  geometry_fieldname = "mygeometry"
  id_fieldname = "myid"
  sql = "SELECT ST_AsBinary(mygeometry) AS mygeometry, myid FROM mytable WHERE mygeometry && !BBOX!"

[[maps]]
name = "mymap"

  [[maps.layers]]
  name =  "mymap"
  provider_layer = "db.mylayer"
  min_zoom = 10
  max_zoom = 20
````

The request:
````
http://localhost:8000/maps/mymap/16/11232/26164.vector.pbf
````

Is there a way to disable it? Or does it come as a layer so I can choose not to render it in the client?
