### ISSUE TITLE
PostGIS: invalid id_fieldname dropping data and not throwing errors

### ISSUE THREAD

**Issue by ARolek** [go-spatial/tegola#382]
The following Provider Layer config passes does not error out during provider initialization or tile requests. The `id_fieldname` is incorrect (id != gid) and the majority of data is being dropped, though not all of it. There is no warning or error detected by tegola. Silent errors like this are difficult to debug.

```toml
[[providers.layers]]
name = "admin_labels"
geometry_fieldname = "geom_3857"
id_fieldname = "id"
sql = "SELECT ST_AsBinary(geom_3857) AS geom_3857, gid, name FROM ne._10m_admin_1_label_points WHERE geom_3857 && !BBOX! AND datarank = 1"
```
