### ISSUE TITLE
Disappearing lakes

### ISSUE THREAD

**Issue by fenelon** [go-spatial/tegola#524]
Between zoom 7 and 8 certain water areas disappear. (i.e. Lake Garda)

![lakes](https://user-images.githubusercontent.com/767838/46602223-341fce80-caf8-11e8-8ab6-30251b895cc4.gif)

I'm using OSM data imported with imposm3.

Tile endpoint: `https://tiles.level.travel/new/maps/osm/{z}/{x}/{y}.pbf`

Provider layers:
```toml
 [[providers.layers]]
  name = "water_areas"
  geometry_fieldname = "geometry"
  id_fieldname = "osm_id"
  sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, COALESCE(tags->'name:ru', tags->'name:en', name) AS name, name AS name_original, type, area, 'water_areas' AS layer_id FROM osm_water_areas WHERE type IN ('water', 'pond', 'basin', 'canal', 'mill_pond', 'riverbank', 'dock') AND geometry && !BBOX!"

  [[providers.layers]]
  name = "water_areas_gen0"
  geometry_fieldname = "geometry"
  id_fieldname = "osm_id"
  sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, type, area, 'water_areas_gen0' AS layer_id FROM osm_water_areas_gen0 WHERE type IN ('water', 'pond', 'basin', 'canal', 'mill_pond', 'riverbank') AND area > 700000000 AND geometry && !BBOX!"

  [[providers.layers]]
  name = "water_areas_gen0_6"
  geometry_fieldname = "geometry"
  id_fieldname = "osm_id"
  sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, type, area, 'water_areas_gen0_6' AS layer_id FROM osm_water_areas_gen0 WHERE type IN ('water', 'pond', 'basin', 'canal', 'mill_pond', 'riverbank') AND area > 60000000 AND geometry && !BBOX!"

  [[providers.layers]]
  name = "water_areas_gen1"
  geometry_fieldname = "geometry"
  id_fieldname = "osm_id"
  sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, type, area, 'water_areas_gen1' AS layer_id FROM osm_water_areas_gen1 WHERE type IN ('water', 'pond', 'basin', 'canal', 'mill_pond', 'riverbank') AND area > 1000 AND geometry && !BBOX!"
```

Map layers:
```toml
  [[maps.layers]]
  name = "water_areas"
  provider_layer = "osm.water_areas_gen0"
  min_zoom = 3
  max_zoom = 5

  [[maps.layers]]
  name = "water_areas"
  provider_layer = "osm.water_areas_gen0_6"
  min_zoom = 6
  max_zoom = 9

  [[maps.layers]]
  name = "water_areas"
  provider_layer = "osm.water_areas_gen1"
  min_zoom = 9
  max_zoom = 12

  [[maps.layers]]
  name = "water_areas"
  provider_layer = "osm.water_areas"
  min_zoom = 13
  max_zoom = 20
```

Then I tried turning simplification off, didn't seem to help:
```toml
  [[maps.layers]]
  name = "water_areas"
  provider_layer = "osm.water_areas_gen0_6"
  dont_simplify = true
  min_zoom = 6
  max_zoom = 8

  [[maps.layers]]
  name = "water_areas"
  provider_layer = "osm.water_areas_gen1"
  dont_simplify = true
  min_zoom = 9
  max_zoom = 12
```

imposm3 mapping.json
```json
"generalized_tables": {
      "water_areas_gen1": {
            "source": "water_areas",
            "sql_filter": "ST_Area(geometry)>50000.000000",
            "tolerance": 50
      },
      "water_areas_gen0": {
            "source": "water_areas_gen1",
            "sql_filter": "ST_Area(geometry)>500000.000000",
            "tolerance": 200
      }
}
```

**Comment by ARolek** [comment]
@fenelon can you try adjusting the `min_zoom` to 5 value on this block:

```toml
  [[maps.layers]]
  name = "water_areas"
  provider_layer = "osm.water_areas_gen0_6"
  min_zoom = 6
  max_zoom = 9
``` 

I think you have a gap there and the water area disappearing might have to do with the browser using the previous zoom levels for that zoom as the tiles are loading in. 

Great looking style btw!
