### ISSUE TITLE
provider/postgis: no error thrown when geoFieldname is not found during decipherFiled processing

### ISSUE THREAD

**Issue by ARolek** [go-spatial/tegola#590]
This is a nasty silent bug. Using the following configuration block for context:

```toml
[[providers.layers]]
name = "water"
geometry_type = "polygon"
geometry_fieldname = "geometry"
sql = "SELECT ST_AsBinary(geometry) FROM layer_water(!BBOX!, !ZOOM!)"
```

No features are rendered by tegola though features are returned by the SQL. The issue here is that `geometry_filedname = "geometry"` is defined but since the `ST_AsBinary(geometry)` does not have `AS geometry` after it, the `geoFieldname` is not found during processing of the result set. Tegola continues moving forward and returns no encoded geometries.
