### ISSUE TITLE
docker debug help - no data coming from port

### ISSUE THREAD

**Issue by swatson26** [go-spatial/tegola#667]
Hi, Im trying to figure out what I'm doing wrong here.
For reproducibility, here is my  zipped config file and geopackage

[config.toml.zip](https://github.com/go-spatial/tegola/files/4067319/config.toml.zip)

[pune_roads.gpkg.zip](https://github.com/go-spatial/tegola/files/4067318/pune_roads.gpkg.zip)

```
docker run -v /Users/steven/tegola/:/opt/tegola_config -p 9090 gospatial/tegola serve --config /opt/tegola_config/config.toml
```
seems to start up fine according to the logs
```
2020-01-15 20:01:00 [INFO] root.go:61: Loading config file: /opt/tegola_config/config.toml
2020-01-15 20:01:00 [INFO] config.go:207: loading local config (/opt/tegola_config/config.toml)
2020-01-15 20:01:00 [INFO] server.go:80: starting tegola server on port :9090
```
but when I go to `http://localhost:9090/` I get a connection refused error

**Comment by ARolek** [comment]
@swatson26 looks like your data is in the 4326 projection:

```console
sqlite> select * from gpkg_geometry_columns;
table_name|column_name|geometry_type_name|srs_id|z|m
pune_roads|geom|LINESTRING|4326|0|0
```

Try adding the `srid` field to the data provider:

```toml
[[providers]]
name = "test_gpkg"   # provider name is referenced from map layers
type = "gpkg"
filepath = "/opt/tegola_config/pune_roads.gpkg"
srid = 4326  # define 4326 SRID
```
