### ISSUE TITLE
Webserver.Headers config cannot be set via environment variables

### ISSUE THREAD

**Issue by ezk84** [go-spatial/tegola#685]
If I have config like:
```toml
[webserver]
port = ":9090"
uri_prefix = "${TEGOLA_URI_PREFIX}"

    [webserver.headers]
	Access-Control-Allow-Origin = "${TEGOLA_ALLOW_ORIGIN}"

...
```
The value isn't picked up from the environment, instead the literal string `${TEGOLA_ALLOW_ORIGIN}` is sent as the header value. Other values are correctly picked up from the environment.
