### ISSUE TITLE
Merge mvt_provider and providers into single providers section in config.

### ISSUE THREAD

**Issue by gdey** [go-spatial/tegola#688]
This is a copy of https://github.com/go-spatial/tegola-postgis/issues/4

with #687 we will have the mvt_provider experiment in the mainline, and so should track currently known issues with it.

Should we remove mvt_provider, and have the provider register as an MVT type provider. 

i.e.
```toml
[[providers]]
name = "test_postgis"       # provider name is referenced from map layers (required)
type = "mvt_postgis"            # the type of data provider must be "postgis" for this data provider (required)
host = "localhost"          # PostGIS database host (required)
port = 5432                 # PostGIS database port (required)
database = "tegola"         # PostGIS database name (required)
user = "tegola"             # PostGIS database user (required)
password = ""               # PostGIS database password (required)
```

There are some things to note about this approach.

1. The provider needs to state that it's an MVT provider (this could be done by look to see if it supports the mvt_provider interface)

2. Documentation can be confusing as mvt providers can not conflate with other providers.

# Errors

If a map has an mvt provider, it can be the only one and the system will error during configuration stating that the mvt_provider can be the only provider.
