### ISSUE TITLE
Question: Non-Geospatial Maps & SRIDs?

### ISSUE THREAD

**Issue by jay-manday** [go-spatial/tegola#730]
Hi there! 

I had a question about non-geospatial maps, my company has been super impressed w/ Tegola and we think it might fit perfectly into our use-case. 

We have a pipeline to convert Blueprints(CAD/PDF) into Raster Tiles & Vectorized data and we're in need of a tile server! Our data is stored in PostGIS in vanilla cartesian coordinates (x, y, WKBs, POLYLINE etc) that don't require projections, in other words `SRID 0`. Can Tegola support Raster (& vector tiles eventually) that don't require geo-projections like Web-Mercator `EPSG 3857`  or `EPSG 4326`?

If you guys can't support it at the moment, totally happy to jam w/ the maintainers to come up w/ a reasonable solution and open a PR. We love Tegola and would be awesome to use it for our problem.

Thanks!

**Comment by ARolek** [comment]
@jay-manday I'm glad you're enjoying tegola! I have not attempted to use vector tiles with data without a SRID, but it might be possible. Are you using ST_AsMVT for generating the vector tiles in PostGIS? If not, that would be the first place I would attempt this. Here's an example provider config block to take advantage of `SA_AsMVT`:

```toml
[[providers]]
name = "cities"
type = "mvt_postgis"
host = "${DB_HOST}"
port = 5432
database = "${DB_NAME}"
user = "${DB_USER}"
password = "${DB_PW}"

	[[providers.layers]]
	name = "cities"
	geometry_type = "polygon"
	geometry_fieldname = "geom"
	id_fieldname = "id"
	sql = "SELECT id, name, ST_AsMVTGeom(geom_3857, !BBOX!) AS geom FROM gis.places WHERE geom_3857 && !BBOX!"
```

I think the crux of this request comes down to informing the reprojection routine to convert between the coordinate space of your blueprints to tile coordinates. I'm not sure if this will work with SRID=0, but I'm sure we can figure out a way to get make it work. 

I'm interested in how this comes together, so please keep me in the loop!
