### ISSUE TITLE
Using ST_AsMVTGeom with SRID 4326 causes rendered polygons to shift North East at low zoom levels

### ISSUE THREAD

**Issue by rodreegez** [go-spatial/tegola#731]
Hey folks, 

I'm encountering a strange issue that I don't understand.

### Actual Behavior
As depicted in [this video](https://www.loom.com/share/2c177e7a3f1c4a0388bdb8d95e7094ee) my polygons make a break for the North Sea as I decrease the level of zoom!

### Expected Behavior
I'd expect the rendered polygons to stay broadly in place.

#### Data used (where to get the data.)
The data I'm trying to render (the U.K. Green Belt) has an SRID of 4326. I'm not really sure how best to share the dataset. Here are a few rows from a rather large table:

```bash
1	Dacorum	E07000096	10641.8521	London area	MULTIPOLYGON (((-0.6823910543879775 51.79442049154736, -0.6820207666365838 51.793914403976984, -0.6819713848363225 51.79383883693092, -0.68181718413316 51.79354116129086, -0.681757008310655 51.793420770858305, -0.6817289000878424 51.793262729024335, -0.6816416907559254 51.792610939463515, -0.682077201068385 51.792543964867356, -0.6836648487770477 51.792397475541435, -0.6835427325127756 51.791829909612915, -0.6834380147509416 51.79091404101849, -0.6822741496507773 51.79063184039543, -0.6819715604338256 51.79053697046843, -0.6801900953184341 51.790129634344986, -0.6792041975193462 51.789911856466006, -0.678539862509953 51.78978285767217, -0.6779668889459732 51.78968447162917, -0.6773787715355224 51.789656799683485, -0.6773438694016111 51.78965738718103, -0.6773016788002109 51.789659304360626, -0.6772699159312111 51.78966062849171, -0.6772449735700208 51.78966175060037, -0.6768733469474261 51.789680048477756, -0.6764042007104336 51.78970174330193, -0.6757583943192862 51.78972201334949, -0.675731184432956 51.789722830861855, -0.6752319103844732 51.78973701541884, -0.6751607226829526 51.78973888387708, -0.674657200470108 51.789758494002605, -0.6740790459092716 51.789789632851196, -0.6736651397913052 51.789812784839214, -0.6733805802603757 51.78982853802452, -0.6728781303029318 51.78985798942243, -0.6724945743427929 51.789881479829646, -0.6724655071260714 51.78988382217019, -0.6720649129747007 51.789900932610315, -0.6719773693260692 51.78990429585588, -0.6718045986865776 51.789785741636045, -0.6718204167682593 51.789771443860104, -0.672037027871634 51.78952381647077, -0.6720965849678283 51.78945536177922, -0.6723361898636423 51.78918002968447, -0.6724074573291118 51.78909837253961, -0.6724463787811322 51.78905371019328, -0.6724792300381808 51.78901530038562, -0.6724942476807851 51.788997630630696, -0.6725134743126341 51.78897536873464, -0.6726969261308722 51.78876108420843, -0.6726938880602696 51.78875641025826, -0.6726912993062227 51.7887517413799, -0.6726517270812589 51.788679784626055, -0.6726482848196629 51.78867356855132, -0.6726121507590964 51.78860797167656, -0.6725635614674956 51.78851918875484, -0.6725493476946693 51.788494166566366, -0.6724948596073567 51.78840531702065, -0.6724737042193774 51.7883698131915, -0.6724455862982182 51.78833985049032, -0.6724142446384994 51.78831154180263, -0.6723833916271904 51.7882823934146, -0.6723635905555609 51.788262496261346, -0.6723323767202445 51.788229837067774, -0.6723143668464049 51.788210661473954, -0.6722711061375689 51.788156223496635, -0.6722654607171678 51.78814801337568, -0.6722419971039467 51.788113607386364, -0.6722213161638712 51.788077263657215, -0.672206486499918 51.788042118937376, -0.6722022531398697 51.78803223434054, -0.672195534044267 51.78801417529882, -0.6722147067000929 51.788009050799, -0.6720905253938415 51.78788710728692, -0.6719283094359495 51.78773326351341, -0.6718463011722531 51.787655908766034, -0.6718357115006041 51.787646231097604, -0.6715200855228332 51.787995450399634, -0.671437671388897 51.788086395267136, -0.6713767733168188 51.788154133141, -0.6713552606182245 51.78817721423278, -0.671271001067565 51.78826926207954, -0.6711848713255002 51.78836326687989, -0.6711057618152616 51.788449762059315, -0.6710228946158494 51.78854027891163, -0.670934436726988 51.788636505111654, -0.6708473741865363 51.78873161407814, -0.6708075631560819 51.78877542063819, -0.6707602922918098 51.78882687561842, -0.6706868064080563 51.78890696913891, -0.6706015937307952 51.78900027354478, -0.6705182730267139 51.78909135138448, -0.670429328543992 51.789188273046875, -0.6704087383452862 51.7892105191877, -0.6703464728483941 51.78927879854472, -0.670255171634439 51.78937892140446, -0.6701629383270535 51.789480157599925, -0.6701573171488997 51.789486415110886, -0.6701226953658251 51.78952381517812, -0.6700464243793672 51.789605845956835, -0.6697483858841133 51.78992602779007, -0.6696351243453291 51.79004852455572, -0.6696192147762021 51.790065905118276, -0.6695482691759355 51.790074795346094, -0.6690512773394568 51.79011862474669, -0.6690121901922139 51.790122956850965, -0.6689335372934418 51.79013162459448, -0.6689158293037788 51.79013324943348, -0.6686494891724232 51.790176172173005, -0.6686348374826228 51.790181347283195, -0.6686097663015265 51.790186827021095, -0.668541348976491 51.79020192248736, -0.6684638248360191 51.79021902781277, -0.6684405384932544 51.79022495033033, -0.668415910570235 51.79023014731582, -0.6684067977700983 51.79023186941177, -0.6683749659286942 51.79023600472657, -0.6683603928023071 51.79023851019191, -0.6683138947102006 51.79024782039966, -0.668213319879375 51.790262839215785, -0.6681318901977727 51.79027371387916, -0.66803267773717 51.79028874797217, -0.6680035563001416 51.79029291388865, -0.6679917349162041 51.79029404779221, -0.6677026630879016 51.79032449132701, -0.6676079975716337 51.79033873137158, -0.6674728133089548 51.7903443658039, -0.6673001337485263 51.790346059416976, -0.6664914155062979 51.79020496632472)) ...etc.... ((-0.4721991445046227 51.82786563968654, -0.472333634100177 51.827885091277295, -0.4721986948388686 51.827865633845484, -0.4721991445046227 51.82786563968654)))	20
```

If I set the provider type to `postgis` and use `ST_AsBinary`, everything works, but is kinda slow, so I'd like to use the `mvt_postgis` provider type, which is much faster but leads to this weird issue.

#### Config file (sanitized version of the config file used.)
When using the `postgis` provider, my config looks like this:

```toml
[[providers]]
name = "${SCHEMA}"      # provider name is referenced from map layers
type = "postgis"    # the type of data provider. currently only supports postgis / mvt_postgis
host = "${DBHOST}"      # postgis database host
port = "${DBPORT}"      # postgis database port
database = "${DBNAME}"  # postgis database name
user = "${DBUSER}"      # postgis database user
password = "${DBPASS}"  # postgis database password
srid = 4326             # The default srid for this provider. If not provided it will be WebMercator (3857)

  [[providers.layers]]
  name = "greenbelt"
  geometry_fieldname="geom"
  id_fieldname="gid"
  geometry_type = "MultiPolygon"
  srid="4326"
  dont_simplify = true
  sql = "SELECT ST_AsBinary(geom) AS geom, gid FROM ${SCHEMA}.greenbelt WHERE geom && !BBOX! and zlevel=!ZOOM!"
```

(I've pre-simplified the geoms for each zoom level, hence passing in the `!ZOOM!` and enabling `dont_simplify`).

Again, this works perfectly and the rendered polygons behave exactly as expected at all levels of zoom, but is kinda slow.

When I switch it to the `mvt_postgis` provider, I update my config to look like this:

```toml
[[providers]]
name = "${SCHEMA}"      # provider name is referenced from map layers
type = "mvt_postgis"    # the type of data provider. currently only supports postgis / mvt_postgis
host = "${DBHOST}"      # postgis database host
port = "${DBPORT}"      # postgis database port
database = "${DBNAME}"  # postgis database name
user = "${DBUSER}"      # postgis database user
password = "${DBPASS}"  # postgis database password
srid = 4326             # The default srid for this provider. If not provided it will be WebMercator (3857)

  [[providers.layers]]
  name = "greenbelt"
  geometry_fieldname="geom"
  id_fieldname="gid"
  geometry_type = "MultiPolygon"
  srid="4326"
  dont_simplify = true
  sql = "SELECT ST_AsMVTGeom(geom, !BBOX!) AS geom, gid FROM ${SCHEMA}.greenbelt WHERE geom && !BBOX! and zlevel=!ZOOM!"
```

It's in this last configuration that the issue of the escaping polygons arises, and I have no idea why.

While trying to figure things out, I found [this](https://gis.stackexchange.com/questions/360197/using-st-asmvt-with-st-tileenvelope-clipping-in-mapbox/360259#360259) StackOverflow answer that seemed to suggest that it might be a problem with the bounding box not scaling properly? However I'm not sophisticated enough to understand if this is indeed even related to the issue I'm seeing, nor how one would implement the solution described in the Tegola config, given that Tegola handles the bounding box stuff through the `!BBOX!` token.

If there is any further information I can provide please let me know. I've been super impressed with Tegola since I've discovered it, thanks for a great tool!

**Comment by ARolek** [comment]
@rodreegez Let's see if we can get to the bottom of this. 

This piece is not the issue, but the `srid`, `dont_simplify` and `geometry_type` config values don't apply when using `mvt_postgis`. This is because all the geometry processing is handled in PostGIS so tegola does not have a chance to utilize those values. They're ignored though, so they should not cause any issues.

I see two potential issues:

* Per your research, the bounding box projection is not matching the projection of the data. The `!BBOX!` is coming in with a 3857 projection. Try reprojecting it to 4326: `ST_Transform(!BBOX!,4326)`.
* It looks like your data has a `zlevel` attribute that you're filtering on. Unfortunately, some systems like to start at zoom 0 and others at zoom 1. Try adding or removing 1 to the `!ZOOM!` token value and see if things line up.

Let me know how this goes!

**Comment by renzeroni** [comment]
Hello, I want to add that I have been experiencing similar behaviour to what @rodreegez described.

My setup involves PostGIS, pg-featureserv and Tegola. However, when using a combination of pg-featureserv and tegola to display data, there appears to be a major shift in the polygons between the source datasets. See the attached images and the descriptions below:

![image_1](https://user-images.githubusercontent.com/62571147/103230960-0c052b80-490d-11eb-8646-ef40ea59c870.png)
Image 1: world countries (served from tegola) along with some other datasets (served from pg-featureserv) at zoom level 0

![image_2](https://user-images.githubusercontent.com/62571147/103230959-0b6c9500-490d-11eb-92ac-e8b1bbf285d6.png)
Image 2: world countries (served from tegola) along with some other datasets (served from pg-featureserv) zoomed in

Hoping you can provide guidance on this.

**Comment by rodreegez** [comment]
Hey @ARolek, thanks for the reply, sorry for the delay in responding - hope you had a good holiday if you were celebrating.

As far as I was able to tell, the `ST_Transform` was already being applied to the bounding box as I had set the `srid` to 4326 in the global config. Setting the SQL debug env var seemed to confirm this:

```sql
SELECT ((SELECT ST_AsMVT(q,'greenbelt',4096,'geom','gid') AS data FROM (SELECT ST_AsMVTGeom(geom,ST_MakeEnvelope(-179.99999997494382,0,-89.99999998747191,66.51326043811893,4326)) AS geom, gid FROM core.greenbelt WHERE geom && ST_MakeEnvelope(-179.99999997494382,0,-89.99999998747191,66.51326043811893,4326) AND zlevel=2 AND mnb_end_date IS NULL) AS q)) AS data
```

I also experimented with the zoom level, but don't believe this to be the issue, either.

That being the case, I wanted to see if I could reproduce the issue using another dataset entierly, so I set up the Getting Started example and switched it over to use MVTs. I've created a repo here: https://github.com/rodreegez/tegola-bonn-mvt and I am able to reproduce the issue, though it isn't as obvious as the Bonn OSM data is comparatively very small and difficult to see while zoomed out that far (I was able to confirm the issue arrises between zoom levels 7 and 6).

To reproduce the issue in the repo above, I needed to supply a basemap to layer the data over. I used Mapbox, as that's what I'm familiar with and what I'm using in the example from which the issue originally arose. I haven't been able to discount the issue being a Mapbox issues rather than Tegola - if anyone has any suggestions of easy ways to layer this data over an alternative basemap I'd be keen to try that - however I do currently think the issue is in how Tegola is handling the bounding box at low levels of zoom.

Please let me know if I can provide any other information, or if there is anything else I can do to help.

**Comment by ARolek** [comment]
@rodreegez no worries! I have been slow to respond too. I have been in the middle of a move, which is always all consuming!

Thanks for standing up the test case. I'm going to find some time to recreate this and see if I can determine what the root of the issue is. it looks like @renzeroni is also having this issue so it's not isolated to just your environment. Let me dig in and see what I can find.

**Comment by ARolek** [comment]
@rodreegez one idea to try (I have not stood up the example yet), is turning off the `srid` config property and then using ST_Transform on the bounding box token like I suggested earlier. I wonder if this would give you different results. Technically it shouldn't, but maybe there's an issue with tegola's reprojection operation.

**Comment by rodreegez** [comment]
@ARolek just tried removing the `srid` declaration from the config and explicitly transforming the `!BBOX!` tokens (both tokens in each of the layers in the Bonn OSM map). Doing so doesn't appear to have changed the result and the jumping behaviour persists.

Hope that helps.

**Comment by ARolek** [comment]
@rodreegez could you post the debug SQL so I can take a quick look at it? At this point, PostGIS is handling pretty much all the computations. Tegola is only responsible for the token replacements. 

@renzeroni what projection is your data in?

I'm still planning on standing up an environment to recreate this, I just won't be able to do so for a few days.

**Comment by renzeroni** [comment]
good day, my data is stored in the dB using EPSG: 4326 and reprojected to Web Mercator (EPSG: 3857) on the web.

**Comment by ARolek** [comment]
@renzeroni thanks for chiming in. I have a deployment of tegola using ST_AsMVT but my data is in 3857 and I'm not seeing this issue. 2 deployments with 4326 source data seeing this issue is helpful to know.

**Comment by renzeroni** [comment]
Let me know what other info you need about my deployment @ARolek. We can get @jj0hns0n to chime in as well.

**Comment by rodreegez** [comment]
Hey @ARolek - small update from me. I've corrected the jumping geoms issue by `ST_Transform`ing the data rather than the bounding box, and removing the `sird` config that was specifying 4326.

For me, the fix was to:

1. remove the config line `sird=4326`
2. update my query to something like this:

```sql
  sql = "SELECT ST_AsMVTGeom(ST_Transform(geom, 3857),!BBOX!) AS geom, gid FROM my_schema.greenbelt WHERE ST_Transform(geom,3857) && !BBOX! AND zlevel=!Z!"
```

This seems to have fixed the issue as reported. @renzeroni would a similar fix work for you?

**Comment by ARolek** [comment]
@rodreegez I agree that tegola should support 4326 with ST_AsMVT, and this SHOULD be working. I appreciate the follow up after you reprojected your data. This does help narrow down the issue. I would suspect this has to do with the `!BBOX!` token , which is why I suggested trying `ST_Transform(!BBOX!, 4326)` in your query. It sounds like this didn't work though so I'm trying to figure out where else the issue could stem from.

**Comment by ARolek** [comment]
I found the issue! `ST_AsMVTGeom()` is expecting the geometries to be in 3857 projection. When your data is in 4326, you want to use the 4326 version of the `!BBOX!` in your `FROM` clause, but you need to transform the geometries and `!BBOX!` to 3857 in the `ST_AsMVTGeom()` statement. 

Here's an example of the natural earth country data: 

```toml
[webserver]
port = ":8080"

# register data providers
[[providers]]
name = "natural_earth"
type = "mvt_postgis"
host = "localhost"
port = 5432
database = "natural_earth"
user = "arolek"
password = ""
srid = 4326

  [[providers.layers]]
  name = "countries"
  geometry_fieldname = "geom"
  id_fieldname = "gid"
  geometry_type = "polygon"
  sql = "SELECT ST_AsMVTGeom(ST_Transform(geom, 3857),ST_Transform(!BBOX!, 3857)) AS geom, name, gid FROM ne_admin_0_countries WHERE geom && !BBOX!"

[[maps]]
name = "natural_earth"

  [[maps.layers]]
  provider_layer = "natural_earth.countries"
  min_zoom = 0
  max_zoom = 20
```

@rodreegez & @renzeroni can you try this approach to see if it works on your end?
