### ISSUE TITLE
cache is based on map not layer level

### ISSUE THREAD

**Issue by peerusman** [go-spatial/tegola#768]
in config.toml i try to create three maps One with all layers and other with one, one layers. 

```toml
[[maps]]
name = "world"
  [[maps.layers]]
  provider_layer = "test_postgis.wells"
  [[maps.layers]]
  provider_layer = "test_postgis.pipelines"

[[maps]]
name = "pipelines"
  [[maps.layers]]
  provider_layer = "test_postgis.wells"
[[maps]]
name = "wells"
  [[maps.layers]]
  provider_layer = "test_postgis.wells"
```

The mistake I did is a copy and paste, in pipelines map. i access the layer and it cashed. now I corrected my mistake

```toml
[[maps]]
name = "pipelines"

  [[maps.layers]]
  provider_layer = "test_postgis.pipelines" 
```

![image](https://user-images.githubusercontent.com/20946339/113542074-87edce80-95f4-11eb-88fe-db1ad110304f.png)

So the pipeline display with invalid tiles from other layer. I think cache should be on the basis on layers. or it looks for validity if map have same layers or not else invalidate cache for that layer only rest can keep if it is not changed.
