### ISSUE TITLE
Cache using Ceph

### ISSUE THREAD

**Issue by flowrean** [go-spatial/tegola#835]
Hi

I am trying to use Ceph for caching using the S3 cache provider. Here's what my config looks like:
```toml
[cache]
type = "s3"
endpoint = "my-endpoint-ceph"
bucket = "my-bucket"
basepath = "my-basepath"
aws_access_key_id = "${CONFIG_S3_ACCESSKEY}"
aws_secret_access_key = "${CONFIG_S3_SECRETKEY}"
```

Tegola fails with the following message:
```
could not register cache: cache: error setting to (s3) cache: RequestError: send request failed
caused by: Put "https://my-bucket.my-endpoint-ceph/my-basepath/tegola-test-map/test-layer/0/0/0": dial tcp: lookup my-bucket.my-endpoint-ceph: no such host
```

Isn't Ceph supported or am I doing something wrong? I'm not sure if the URL looks correct.
