### ISSUE TITLE
Params for SQL query not working

### ISSUE THREAD

**Issue by jmcaracoche** [go-spatial/tegola#910]
I've been dealing with this issue for some days. I didn't find anything in the web and I read the code and should work but it's no working for me.

I'm running the compiles version 0.16.0

I have this section in my config.toml file

```toml
[[providers.layers]]
  name = "harvest_map"
  geometry_fieldname="geometry"
  id_fieldname="gid"
  #geometry_type="Point"
  sql = """SELECT ST_AsMVTGeom(geometry,!BBOX!) 
        AS geometry, gid,  yield_, collection_id, crop 
        FROM harvest_map WHERE geometry && !BBOX!  !PARAM!"""

[[maps.params]]
name = "collection_id"        
token = "!PARAM!"      
type = "string"       
sql = "AND collection_id = ?" 
default_sql = " "   
```

I get this error when launching the server

{"level":"debug","timestamp":"2023-03-11T16:18:06.272-0300","message":"SQL for Layer(harvest_map):\nSELECT ST_AsMVTGeom(geometry,!BBOX!) AS geometry, gid,  yield_, collection_id, crop FROM harvest_map WHERE geometry && !BBOX! !PARAM! \n"}
Error: could not register providers: error fetching geometry type for layer (harvest_map): ERROR: column "param" does not exist (SQLSTATE 42703)

If I change the token to something else line !PARAM2!, the error is

Error: could not register providers: error fetching geometry type for layer (harvest_map): ERROR: column "param2" does not exist (SQLSTATE 42703)

Whatever I use as token it's appear as a column X does not exists.

Is this a bug or I'm doing something wrong?

Thank you in advance.
