### ISSUE TITLE
Add custom params to sql query is not working

### ISSUE THREAD

**Issue by navot-tomorrow** [go-spatial/tegola#911]
I have an issue with my config.toml configuration.
This is my config.toml file:(I removed the webserver and providers section)

```toml
[[providers.layers]]
name = "locations"
geometry_fieldname = "geometry"
id_fieldname = "vector_tile_id"
geometry_type = "Point"
fields = []
sql = "SELECT ST_AsBinary(geometry) AS geometry,vector_tile_id FROM events.locations WHERE geometry && !BBOX! !PARAM!"


[[maps]]
name = "monitors-events"

[[maps.layers]]
name = "locations"
provider_layer = "monitors-events.locations"

[[maps.params]]
name = "accountId"
token = "!PARAM!"
type = "string"
sql = "AND acc_id = ?"
default_sql = "123"
```

this is my tegola start command:
serve --config /opt/config/config.toml

this is my image:
image: gospatial/tegola

this is my error I see in the container:
[ERROR] map.go:342: err fetching tile (z: 0, x: 0, y: 0) features: error running layer (locations) SQL (SELECT ST_AsBinary(geometry) AS geometry,vector_tile_id FROM events.locations WHERE geometry && ST_MakeEnvelope(-185.62499997416083,-85.5133983078662,185.62499997416083,85.5133983078662,4326) !PARAM!): ERROR: syntax error at end of input (SQLSTATE 42601)

I have 2 questions:
1. What do I need to change to fix the error and return locations based on the custom param?(acctId in my example)
2. I want to return in the same response Point and Polygon, is it possible? If I remove the geometry_type in the provider layer the tegola server is crashed.

Thanks!
