### ISSUE TITLE
Set Tile Resolution / Extent

### ISSUE THREAD

**Issue by wroge** [go-spatial/tegola#955]
Unfortunately, my generated Vector Tiles are incorrect...
Previously I created my Vector Tiles with T-Rex, specifying a resolution of 16384. However, with Tegola, I am unable to configure the tile extent of the ST_AsMVT PostGIS function. (Default: 4096)

<img width="769" alt="Bildschirmfoto 2023-10-11 um 13 25 30" src="https://github.com/go-spatial/tegola/assets/44040384/338a7a9b-14a3-4b17-bf64-c39af0067358">

https://github.com/go-spatial/tegola/blob/master/provider/postgis/postgis.go#L1029
```go
sqls = append(sqls, fmt.Sprintf(
	`(SELECT ST_AsMVT(q,'%s',%d,'%s',%s) AS data FROM (%s) AS q)`,
	layers[i].MVTName,
	tegola.DefaultExtent,
	l.GeomFieldName(),
	featureIDName,
	sql,
))
```

My config: 

```toml
[[providers]]
# ...
type = "mvt_postgis"
uri = "${PG_CONNECTION}"
srid = 3857

[[providers.layers]]
# ...
geometry_type = "POLYGON"
id_fieldname = "objectid"
geometry_fieldname = "wkb_geometry"
sql = "SELECT ST_AsMVTGeom(ST_Transform(geom, 3857), ST_Transform(!BBOX!, 3857)) AS wkb_geometry, objectid FROM my_table WHERE ST_Transform(geom, 3857) && ST_Transform(!BBOX!, 3857)"

[[maps]]
# ...
bounds = [6.3, 51.25, 11.6, 54.17]
center = [10.023321918554046, 52.44665611695578, 15.0]
tile_buffer = 150

[[maps.layers]]
# ...
min_zoom = 12
max_zoom = 15 
dont_simplify = true
```

If desired, I can try to provide a pull request.
