### ISSUE TITLE
Support for S3 Accelerated Bucket Endpoint in Cache Configuration

### ISSUE THREAD

**Issue by AISuhasDattatreya** [go-spatial/tegola#991]
We are currently using Tegola and would like to leverage S3 Transfer Acceleration for our cache. However, the current documentation and configuration options do not seem to support specifying a custom S3 accelerated endpoint.

Could you please add support for specifying a custom S3 endpoint in the cache configuration? This feature would greatly enhance our caching performance.

**Comment by iwpnd** [comment]
[This](https://github.com/go-spatial/tegola/tree/master/cache/s3#properties) should suffice, does it not?

**Comment by AISuhasDattatreya** [comment]
Thank you for your response. Could you clairify where we'd add the accelerated endpoint? Presently, we've added the s3 cache configuration on the toml and enabled transfer acceleration on s3. But when on the browser network we're still seeing cache being served from the non-accelerated endpoint.


```
[cache]
type = "s3"
bucket = "${AWS_CACHE_BUCKET}"
region = "${AWS_REGION_1}"
aws_access_key_id = "${AWS_ACCESS_KEY_ID_1}"
aws_secret_access_key = "${AWS_SECRET_ACCESS_KEY_1}"
```

**Comment by iwpnd** [comment]
Disclaimer, I’ve not worked with accelerators, so it’s trial and error. But you could try to add it in `endpoint`.
If this does not work, I’m happy to investigate this. 👍

**Comment by ARolek** [comment]
I read up on the accelerators last night and it seems like you just need to enable the transfer accelleration capability on the bucket and then adjust the s3 endpoint to use. Here are the docs: https://docs.aws.amazon.com/AmazonS3/latest/userguide/transfer-acceleration-getting-started.html

@AISuhasDattatreya your `[cache]` block could be adjusted to the following:

```toml
[cache]
type = "s3"
bucket = "${AWS_CACHE_BUCKET}"
region = "${AWS_REGION_1}"
# this will need to be an env var, but giving you an example of the format
endpoint = bucketname.s3-accelerate.amazonaws.com 
aws_access_key_id = "${AWS_ACCESS_KEY_ID_1}"
aws_secret_access_key = "${AWS_SECRET_ACCESS_KEY_1}"
```

Side note, you could probably remove `aws_access_key_id` and `aws_secret_access_key` from your config. The AWS Go SDK will infer this from your environment so your infrastructure can manage access control. It's considered more secure to do it this way.
